### ISSUE TITLE
Update CSS of the UI

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/react30_1_id_card_generator#1]
Update the CSS files or complete code of the UI for generating user details cards.
Submissions by multiple contributors to this issue are allowed.
Steps to contribute:
1. Comment on this issue if you are interested in building your own version
2. Wait for being assigned to the issue and getting solution number
3. Once solution number is assigned, clone the repository and create a folder `solution_[your_assigned_number]` in the repo.
    For example, if `solution_3` is assigned to you then you need to create a folder `solution_3` in this repo.
4. If you are a beginner who would only like to modify CSS then copy the code from `solution_1` folder into your assigned folder. If you know want to build your own solution then copy the code from `1_starter_code` into your assigned folder.
5. Once finished, submit your solution as a pull request to this repository. 

Note: No pull request will be accepted until you are added as an assignee to this issue.
An example of updated UI could be as shown below:
<img src="https://res.cloudinary.com/dk22rcdch/image/upload/v1602007711/Blogimages/UpdatedUI_f1d53y.png" height="400" />

**Comment by codeclassifiers** [comment]
Open a PR to 'solution' branch since 'master' is the branch containing problem statement and latest problem solution code is in `solution` branch.

**Comment by carlacentenor** [comment]
Can you assign me to work on this? Thanks !

**Comment by saurabhnative** [comment]
@carlacentenor I have assigned the issue to you as requested.   
Resources for design in the screenshot:-   

- Color code and assets: [Adobe XD](https://xd.adobe.com/view/0a60e909-32ac-4347-ad8d-c863f81a4b77-5f33/specs/)

- Font family used was [Monserrat](https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat:wght@400;500;600;700)

- And font icons used in forms are from [Fontawesome](https://fontawesome.com/cheatsheet?from=io)

You can either build using these resources or as per your own design.
Also please make sure to add the solution to folder `solution_2` as I have done in `solution_1` folder.
If any other help is needed then let me know in comments.

**Comment by carlacentenor** [comment]
Hello :
I have  questions : 

I create a new folder solution_2? 
In this new folder solution_2 , I add my solution ?

**Comment by saurabhnative** [comment]
@carlacentenor Yes, that is the correct approach.

**Comment by saurabhnative** [comment]
@carlacentenor Your solution has been merged. Thank you for your contribution.
I have updated the README of main repository with preview of your solution.

**Comment by saurabhnative** [comment]
@all-contributors please add @carlacentenor for adding solution_2 to this project

**Comment by ellu-laitinen** [comment]
Hi, I'd like to be assigned to this issue!

**Comment by saurabhnative** [comment]
@ellu-laitinen You have been added in the assignee list. You can submit your solution in `solution_3` folder.

**Comment by sandhyanimbark** [comment]
please let me in

**Comment by saurabhnative** [comment]
@tispn You have been added as an assignee. You can submit your solution in `solution_4` folder. 
Please refer to contributions by previous assignees and make changes in your submitted [pull request](https://github.com/codeclassifiers/react30_1_id_card_generator/pull/10) accordingly.
Let me know if you need any help in updating the pull request.
