### ISSUE TITLE
Update README.md with sample learning resources

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/react30_1_id_card_generator#3]
Update the README file for this project with some links containing learning resources for coding in Javascript.

**Comment by jordanhilado** [comment]
Hello, I would like to contribute. May I be assigned to this?

**Comment by saurabhnative** [comment]
@jordanhilado You have been assigned this issue. Feel free to submit your Pull Request

**Comment by jordanhilado** [comment]
Addressed this issue in PR #8 @codeclassifiers

**Comment by sandhyanimbark** [comment]
may i go for it

**Comment by saurabhnative** [comment]
@jordanhilado Thank you for your contribution. I have added relevant labels as per official Hacktoberfest guidelines and merged the pull request.

**Comment by saurabhnative** [comment]
@tispn You have been added as an assignee. Feel free to contribute to this repository. You can refer to Markdown cheatsheet for adding relevant links [here](https://www.markdownguide.org/cheat-sheet/)

**Comment by divyxnsh** [comment]
Hi, I would like to contribute to this

**Comment by aamankumarsh** [comment]
hi, I would like to contribute to this.

**Comment by JiriJAdam** [comment]
Hello, I would like to contribute to the READ.me files for educational links for all languages.

**Comment by saurabhnative** [comment]
@JiriJAdam I am currently only accepting contributions related to Javascript resources. If you can add any of them then feel free to submit a PR.

**Comment by ghost** [comment]
Hello, Buddy, I would like to contribute, Am I allowed..???

**Comment by ayushisingla** [comment]
Hello, I would like to contribute to this.

**Comment by saurabhnative** [comment]
@Mafia15 and @ayushisingla You have been added as assignees. Feel free to contribute to this repository. You can refer to Markdown cheatsheet for adding relevant links [here](https://www.markdownguide.org/cheat-sheet/)

**Comment by sudeephiremath** [comment]
i would love to contribute here, can i

**Comment by Ricktho1** [comment]
Hi, I would like to contribute here for the Hacktoberfest 2022 .
